### ISSUE TITLE
API: Delete endpoints need to return 204

### ISSUE THREAD

**Issue by KevinJJackson** [USACE/instrumentation#10]
Delete Endpoints (or any endpoints that do not return content) need to have the correct status code of 204 or return at minimum an empty object `{}`

cc @brettpalmberg

**Comment by brettpalmberg** [comment]
Any endpoints previously returning `NoContent()` (200 - StatusOK) have been modified to return an empty object `{}` (200 - StatusOK). Changes merged to develop - @KevinJJackson - feel free to re-open if switching 200 --> 204 is critical.
