### ISSUE TITLE
Map Zooms to Florida on Component Render

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/instrumentation#103]
The `explorer` map defaults to a location in Florida when it first renders.

![image](https://user-images.githubusercontent.com/29417036/115628128-c27a8b00-a2c5-11eb-9500-7e9c54a2a673.png)

This worked well for the application when it was specifically focused on Lake Okeechobee; however, recommend we make the following change now that the application supports a wider geographic area of interest:

1. Initialize the map with a center/zoom focused on the continental United States.  Something like: `{{ center: [-98.6, 39.8], zoom: 4 }}` applied here in the code: https://github.com/USACE/instrumentation-ui/blob/5b2d299b16b30fdcdc6052d5f4c19b3ee147982f/src/app-pages/explorer/explorer.js#L62

2. [Pan/Zoom/Fly](https://openlayers.org/en/latest/examples/animation.html) to the location of the instruments in the map after data is fetched and the layer is added to the map

**Comment by KevinJJackson** [comment]
Fixed in my current branch alongside the project landing page, will update this issue when it hits dev environment
