### ISSUE TITLE
[BUG REPORT]: Constant Values Not Saving Past UI

### ISSUE THREAD

**Issue by lucasb16-exe** [USACE/instrumentation#119]
## Describe the bug
Constants can be declared for an instrument, but added values to the constant are not saving or usable in the formula editor. Values can be added to the declared constant, but after switching tabs or menus, the values disappear.

## Steps To Reproduce
1. Open any instrument in MIDAS Stable
2. Navigate to the 'Constants' tab
3. Declare a constant
4. Add a value to the constant
5. Change tabs (try to use the formula editor with the new constant)
6. Go back to the 'Constants' tab
7. The value you added will be gone

## Expected behavior
Utilize constant values for the formula editor

## Actual behavior
Constant values appear to not save past the UI

## Screenshots
![constantbugreport1](https://user-images.githubusercontent.com/55309502/120549550-5d807d80-c3b9-11eb-984c-9375be562f50.PNG)
![constantbugreport2](https://user-images.githubusercontent.com/55309502/120549560-61140480-c3b9-11eb-9ccd-f4f0c793782e.PNG)
![constantbugreport3](https://user-images.githubusercontent.com/55309502/120549565-63765e80-c3b9-11eb-94ce-d9e2a1fa7ea8.PNG)
![constantbugreport4](https://user-images.githubusercontent.com/55309502/120549579-65d8b880-c3b9-11eb-8812-6dd5ab3c19f7.PNG)

## Desktop:
 - OS: Windows 10
 - Browser: Chrome
 - Version 90.0.4430.212

## Additional context
Investigating with Jeff Gregory

**Comment by jeffsuperglide** [comment]
I've confirmed this in stable and develop.  The added constant shows in the formulas tab but doesn't not result in a working formula.

Looking at DevTools shows that adding a value for a constant it is not making a `request`.  Additionally, deleting the `constant` keeps the `constant` on the page until it is refreshed.

**Comment by KevinJJackson** [comment]
After a bit of tweaking, I was able to get the values to successfully update as well as new values persisting. I was also able to get constant deleting to remove right away, instead of needing a refresh. However, there is a bit of a glitch on the API side of things where updating the date-time causes row duplication. This along with the ability to delete particular entries will be added when @dliang864 is able to make the changes in the api early next week.

I'll keep this issue updated as more info becomes available.

**Comment by KevinJJackson** [comment]
@lucasb16-exe - This should be working now in dev. Sorry for the delay, was hoping we get some more fixes around constants as part of this work.

As of now, creating a new constant will persist. You can also go back and update the **value** of any of them. However, we are still working out some details on how we can go about **updating the time** and **deleting a value** altogether.

**Comment by lucasb16-exe** [comment]
@KevinJJackson Sounds great, thanks Kevin. Any expectation yet for when we could see it in stable?

**Comment by lucasb16-exe** [comment]
Constants are saving with latest patch, resolving bug
