### ISSUE TITLE
[BUG REPORT]: Creating a new Timeseries. 

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#147]
## Describe the bug
User tries to create a timeseries, It appears to work but with "Undefined" as "Parameter" and "Unit", but it isn't really created.

## Steps To Reproduce
1. go to an instrument, click timeseries tab, click New Timeseries,  Enter something like "DTW", "Length", "Feet"

## Expected behavior
A timeseries is saved with the parameter and units given.

## Actual behavior
Timeseries is grayed out in UI and not saved. 

## Screenshots
<img width="955" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/73a41eca-db18-47cb-86cd-d03dbc455b12">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 119.0.2151.93

**Comment by KevinJJackson** [comment]
@ScottMassa - Found the issue with this, will let you know when the fix gets deployed and tag you on the associated PR as well.
