### ISSUE TITLE
[BUG REPORT]: UI will not save updated Station and Offset

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#150]
## Describe the bug
User tries to modify the station and offset, updated values are seen, but not saved.

## Steps To Reproduce
Edit instrument, modify station and offset, click save, the UI shows the new values, but it is not saved. 

## Expected behavior
new values are expected to be saved.

## Actual behavior
Not saved, API error. ( see screenshot below)

## Screenshots
<img width="955" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/491f2a3d-6108-4d67-9fa1-c91e6a8bc955">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Microsoft EDGE
 - Version 120.0.2210.77

## Additional context
User also mentioned similar when adding constants or timeseries to an instrument.

**Comment by ScottMassa** [comment]
Also similar behavior when adding instruments to plot groups. i try to add an instrument and after saving it doesn't appear in the plot groups. no put error in MS Edge inspector this time.

**Comment by dennisgsmith** [comment]
@KevinJJackson The PUT payload sent to `/projects/:project_id/instruments/:instrument_id` should include `type_id` field, instead it's null.

I'll look into the instrument group issue separately and report back.

**Comment by dennisgsmith** [comment]
> Also similar behavior when adding instruments to plot groups. i try to add an instrument and after saving it doesn't appear in the plot groups. no put error in MS Edge inspector this time.

This was a separate bug, fix pushed to develop in https://github.com/USACE/instrumentation-api/pull/203

Stable fix is scheduled for next release.

**Comment by dennisgsmith** [comment]
Fixed deployed in https://github.com/USACE/instrumentation-api/pull/210
