### ISSUE TITLE
[BUG REPORT]: Uploader doesn't let us select instrument for TS measurement.

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#161]
## Describe the bug
Uploader doesn't let us select instrument for TS measurement., Does not allow upload of data.

## Steps To Reproduce
1. Go to uploader tab
2. Select CSV file to upload, 
3. Select Timeseries measurement
4. Try to select appropriate instrument "maybe PZ-1"

## Expected behavior
A dropdown box would allow us to select the appropriate instrument/timeseries, a list of all timeseries

## Actual behavior
Only displays Timeseries, date, and reading

## Screenshots
<img width="955" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/0050f551-1329-45a5-82ef-982e15eadb4b">

## Desktop (please complete the following information):
 - OS: Win 10
 - Browser Microsoft Edge
 - Version 121.0.2277.83

**Comment by dennisgsmith** [comment]
Fixed with https://github.com/USACE/instrumentation-ui/pull/209
