### ISSUE TITLE
Filter Parameter List By Instrument in Formula Editor

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#164]
## Describe the bug
The Formula Editor now shows instrument timeseries name as requested instead of slug. It also shows all timeseries per project. Problem is its unclear which timesieries is which. The name "riser" is shown multiple times for example. 

## Steps To Reproduce
1. Go to instrument screen
2. Click on formula editor
3. Scroll down to see multiple entries

## Expected behavior
Available parameters would be instrument and timeseries.  Maybe the instrument shown on the page would be listed first, then other options (maybe searchable) would be below. 

## Actual behavior
Large list of parameters, not sure which is which.

## Screenshots
<img width="995" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/47ff4007-7a13-40f6-95a2-204ff6827692">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser:  Microsoft Edge
 - Version 121.0.2277.128

**Comment by dennisgsmith** [comment]
@ScottMassa Thank you for filing a bug report. @KevinJJackson and I are assessing this issue and working towards a fix.

**Comment by dennisgsmith** [comment]
Hi @ScottMassa  -- after discussing this with @KevinJJackson, it seems like the most straightforward solution would be to simply use the entire variable in the lefthand list, in order to more easily differentiate which instrument the parameter belongs to, while still allowing cross-instrument formulas to exist. The proposed change would change the list on the left as follows:
```
battery   -> test-instrument-1.battery
battery-2 -> test-instrument-2.battery-2
battery-3 -> test-instrument-3.battery-3
```
This will reflect exactly as they appear in the formula editor after double-clicking the parameter. Feel free to provide any feedback you have on this solution.

**Comment by ScottMassa** [comment]
I think this looks good. Is there any way show only the instrument, then click a button to expand to all the others? Some projects may show several hundred timeseries to choose from.

**Comment by KevinJJackson** [comment]
@ScottMassa - Merged the initial change to be able to visually differentiate the timeseries. We will come back to this issue after our main priorities are completed and adjust this further.

**Comment by KevinJJackson** [comment]
@ScottMassa - Updating this to have timeseries sorted underneath their respective instrument. Here is the proposed UI:

![Image](https://github.com/user-attachments/assets/8cbf6d59-ce29-4358-8871-fccd47d629cf)

Does this look acceptable for the use case described above? We can also add a search bar within each instrument or a general search bar that could have all the timeseries (again grouped by instrument) outside the boxes, similar to what we added to the Plotting screen, where selecting an item from the dropdown would act the same as double clicking the timeseries as current:

![Image](https://github.com/user-attachments/assets/f044039e-a531-425f-a2fd-ee123c12402a)

**Comment by KevinJJackson** [comment]
Went ahead with the global search:
![Image](https://github.com/user-attachments/assets/278c7959-87f6-4aff-bafd-0404d9e79267)

**Comment by ScottMassa** [comment]
Can we use "Names" instead of slug/variable in these?  It would be more friendly to the user and reflect changes if they were made, unlike the slugs.  Some slugs/variables are like the following and the user doesn't need to know we have over 2 C2s > 1673 depths to water.  c2-3.depth_to_water-1673

**Comment by dennisgsmith** [comment]
Going to spin this out into its own ticket since it's different from the original one submitted, which has been merged.

Now tracking variable rename request in https://github.com/USACE/instrumentation/issues/209
