### ISSUE TITLE
[BUG REPORT]: Mask Fields not working

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#165]
## Describe the bug
The mask field does not store the current status when boxes are selected

## Steps To Reproduce
1. Go to instrument screen
2. Click on timesieries, click a value that needs to be masked, It does not retain the check mark.

## Expected behavior
When a box is selected the state is stored

## Actual behavior
When a box is selected the state is not stored

## Desktop (please complete the following information):
 - OS: Win 10
 - Browser Microsoft Edge

**Comment by KevinJJackson** [comment]
Thanks for the report, we are investigating this issue and will report back when a solution is found.

**Comment by dennisgsmith** [comment]
Closed with [#215](https://github.com/USACE/instrumentation-ui/pull/215)
