### ISSUE TITLE
[BUG REPORT]: Unable to submit new evaluations

### ISSUE THREAD

**Issue by KevinJJackson** [USACE/instrumentation#166]
## Describe the bug
Attempting to fill evaluation form, clicking submit button produces an error toast message.

## Steps To Reproduce
1. Go to QA/QC Tab
2. Click New Evaluation
3. Fill form until submit button is accessible
4. click submit
5. error message shows

## Expected behavior
A new evaluation is submitted successfully.

Posting on behalf of [@ScottMassa](https://github.com/ScottMassa)

**Comment by dennisgsmith** [comment]
Fixed with https://github.com/USACE/instrumentation-ui/pull/218
