### ISSUE TITLE
[BUG REPORT]: Collection Groups

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#167]
## Describe the bug
When adding a new Collection Group, on the dashboard tab, it fails to save a new collection group 

## Steps To Reproduce
1. Go to dashboard tab
2. Click on collection group add name and click  save. 
3. see error message in network tab of inspect screen.

## Actual behavior
in inspect screen:
    "message": "ERROR: inconsistent types deduced for parameter $2 (SQLSTATE 42P08)"

## Screenshots
<img width="955" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/c0a1b7b2-caf2-4792-a97a-5a18b3c71fbc">

## Desktop (please complete the following information):
 - Browser [e.g. Microsoft Edge]
 - Version [e.g. 90.0.818.46]

**Comment by dennisgsmith** [comment]
Fixed with https://github.com/USACE/instrumentation-api/commit/bf6925b3dfc3e767c7928d2efe44f8f6d6bc55f4
