### ISSUE TITLE
[BUG REPORT]: Unable to Login 

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#173]
## Describe the bug
Users cannot login to MIDAS

## Steps To Reproduce
1. Go to MIDAS
2. Click on Login
3. Nothing happens

I then inspected the site and saw no response from https://corpsmap-dev.sec.usace.army.mil/cwbi/goauth/token/(my uuid)

## Screenshots
<img width="953" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/07a2ca11-8d49-4b21-bb6b-ae35e6152a2b">

<img width="435" alt="image" src="https://github.com/USACE/instrumentation/assets/144471850/74faffc2-277c-4afb-9d3b-140fc18a69b8">

## Desktop (please complete the following information):
 - OS: Windows10
 - Browser : Microsoft Edge

**Comment by dennisgsmith** [comment]
@ScottMassa Thanks for reporting this issue. At a glance it seems that is is an issue with the authentication server rather than MIDAS calling it. I will investigate to confirm this and report this to CWBI as needed.

**Comment by dennisgsmith** [comment]
@ScottMassa I have tested and confirmed this behavior on my end. I found that there is currently an open issue in CWBI tracking this: https://jira.il2.dso.mil/browse/CWBI-21855
I will push toward getting this resolved and keep you updated as the ticket progresses.

**Comment by Rockscientist** [comment]
Thanks!

**Comment by dennisgsmith** [comment]
This issue has been resolved, but has resulted in effort to migrate to CWBI Keycloak instance.
