### ISSUE TITLE
[BUG REPORT]: Plotting Tab crash

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#176]
## Describe the bug
When using the batch plotting screen you can open a plot, then click the plot to interact with it. Then selecting a new plot will cause an error. 

## Steps To Reproduce
1. Go to plot screen
2. Click on a plot, interact with it.
3. click on a new plot, there will be an error and it will display a white screen. must navigate back to the project.
4. See nothing on the screen

## Expected behavior
A new plot that is selected will be displayed.

## Actual behavior
app crashed

## Screenshots
<img width="521" alt="image" src="https://github.com/user-attachments/assets/e85b48c1-98b2-4f36-bdda-8a00cb42b196">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Microsoft Edge 126.0.2592.113

**Comment by KevinJJackson** [comment]
Thanks for creating this report. I believe I've found the root cause of this issue, I will keep this ticket up to date as it gets fixed.
