### ISSUE TITLE
[BUG REPORT]: Missing Mask, Validated, Annotation Fields

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#178]
## Describe the bug
Missing Mask, Validated, Annotation Fields

## Steps To Reproduce
1. Go to Instrument screen, Timesieries tab

## Expected behavior
Be able to mask data

## Actual behavior
No mask field exists

## Screenshots
<img width="603" alt="image" src="https://github.com/user-attachments/assets/72b304ab-75f0-487e-94d8-c2ba2b7f23a8">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Microsoft Edge, 127.0.2651.98

**Comment by KevinJJackson** [comment]
@ScottMassa - Thanks for reporting, this issue was already being tracked and will be fixed in the next release. I will tag the corresponding PR and close this ticket upon completion.

**Comment by dennisgsmith** [comment]
Closing as completed.
