### ISSUE TITLE
[BUG REPORT]: MIDAS Login with Login.gov

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#179]
## Describe the bug
Remnants of old login system still in place

## Steps To Reproduce
Login from Gov Computer

## Expected behavior
Directed to Login.Gov after clicking on Login

## Actual behavior
ActivClient asks for PIN, Then Directed to create profile.

## Screenshots
![image](https://github.com/user-attachments/assets/f95e9db5-f68e-4445-bd70-58efbc552bf6)
![image](https://github.com/user-attachments/assets/481cc2fe-bff2-4d8f-8f67-b070311e5ff3)
After CTRL+R and navigating back to https://midas.sec.usace.army.mil/midas/
![image](https://github.com/user-attachments/assets/c5d01317-775d-41e9-b88d-1f16d5d0fafe)

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Edge

**Comment by dennisgsmith** [comment]
Hi Scott, we suspect there was a caching issue -- I have deployed a fix for this. Please let me know if this issue persists.

**Comment by dennisgsmith** [comment]
Closing as fixed, please reopen if this issue persists.
