### ISSUE TITLE
Crash Upon Accessing/Creating Collection Group

### ISSUE THREAD

**Issue by lucasb16-exe** [USACE/instrumentation#18]
![CollectionGroupError](https://user-images.githubusercontent.com/55309502/104377090-8926c800-54eb-11eb-979a-b0d5fa5753dc.PNG)
Application crashes to white screen when attempting to create or access a collection group. See attached screenshot with error.

RangeError: Invalid time value

Not sure where a date object is getting passed containing an invalid date when just accessing a collection group

If any other information is needed let me know, any input would be appreciated
-Lucas

**Comment by jeffsuperglide** [comment]
Looked at "Indiana Harbor" with @lucasb16-exe on this issue and it was reproducible.  I then tested `Collection Groups` for `Buffalo District Streamgages`.  Successfully added a group and timeseries to that group.  First difference between the two tested is Buffalo has data in timeseries and Indiana does not.  Further investigation into `Collection Groups` for projects without data.

**Comment by lucasb16-exe** [comment]
Found source of error in [collectiongroup-timeseries-list.js](https://github.com/USACE/instrumentation-ui/blob/develop/src/app-pages/collectiongroup/collectiongroup-timeseries-list.js) line 52.

Looks like `item.latest_time` is passed into `parseISO()` without a check to see if it exists, if a timeseries selected for a collection group doesn't have any data, null value will be passed in causing crash.

Signing off for today, will fix via ternary tomorrow morning and pull.

**Comment by lucasb16-exe** [comment]
Potential fix - line 52 -> `{item.latest_time != null ? formatDistanceToNow(parseISO(item.latest_time)) + ' ago' : 'No Data Found'}`
