### ISSUE TITLE
[BUG REPORT]:Edit instrument screen

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#180]
## Describe the bug
Changes made to an instrument do not update the API

## Steps To Reproduce
go to an instrument, edit station and offset, click save.

## Expected behavior
API Post is successfull

## Actual behavior
API returns 400 Bad Request in inspector, also save button does not dismiss instrument screen

## Screenshots
<img width="957" alt="image" src="https://github.com/user-attachments/assets/b64a231f-d0a0-45f4-a5b6-effc65e59075">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 127.0.2651.105

**Comment by dennisgsmith** [comment]
@ScottMassa Thanks for this report, we are currently looking into this issue and will update you on the status once resolved.

**Comment by dennisgsmith** [comment]
Fixed in https://github.com/USACE/instrumentation-ui/pull/234
