### ISSUE TITLE
Custom Order of Collection Groups - MIDAS Improvements (7b)

### ISSUE THREAD

**Issue by madisonschattenfield** [USACE/instrumentation#185]
### **DESCRIPTION**

Collection Groups should allow the user to customize the order, and have that order be retained. When adding a field to the collection group, the instrument picklist should be searchable and alphabetized.

**Comment by ScottMassa** [comment]
FYI, The collection groups order started changing around when data was submitted for a user today, first this has been seen. SAB went from top to bottom of the list. (images below if they make it into Github.)
***@***.***
***@***.***

**Comment by dennisgsmith** [comment]
@ScottMassa Thanks for the info -- your images did not make it to GitHub, I believe you would need to use the browser for this. Either way, this feature should take care of that issue. We can review how we're prioritizing these features and make any adjustments as needed in next week's Sprint Planning.

**Comment by dennisgsmith** [comment]
Closed with
https://github.com/USACE/instrumentation-api/releases/tag/v3.5.0
https://github.com/USACE/instrumentation-ui/releases/tag/v0.18.0
