### ISSUE TITLE
[BUG REPORT]:Incorrect timeframe sometimes passed measurements query when using plot configuration

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#192]
## Describe the bug
Plot screen does not work as expected, it is very slow and becomes non-responsive.

## Steps To Reproduce
Go to plot screen, click on a plot to render.

## Expected behavior
Has performance like it did a week ago.
<img width="954" alt="image" src="https://github.com/user-attachments/assets/42833770-7332-40eb-82c6-7f1185dfe273">

## Actual behavior
Plots are slow or do not load. page hangs.
<img width="948" alt="image" src="https://github.com/user-attachments/assets/4483a21d-de1d-49f3-85d5-ba7bca913cb7">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 127

**Comment by dennisgsmith** [comment]
Hi @ScottMassa --

I'm testing this on my end, but unable to reproduce this issue. I noticed that in the first screenshot, I see only one month of data is being queried. In the second screenshot you sent, where you said the page hangs, the "Lifetime" parameter is selected.

Still I'm testing on this same dataset (InclinometerC1, Bluestone dam) now, and I'm unable to reproduce the issue. The response times for most traces are under 500ms, with the longest taking ~2 seconds.

There is definitely room for improvement when it comes to the performance of querying historical timeseries data, but I'm unable to replicate any regression.

I do, however, see a bug that maybe affecting the query:
<img width="1101" alt="Screenshot 2024-08-23 at 2 25 56 PM" src="https://github.com/user-attachments/assets/789827aa-5303-4855-a0c3-a7d349d95cf7">

The `after` and `before` parameters are extremely low, even though "lifetime" is selected. This is likely the reason that no data is showing on the plot as well. @ScottMassa Were there any specific actions you took in MIDAS before encountering this issue and are you able to replicate the issue consistently?

I'm going to update this issue to describe this bug -- we can discuss performance more generally in our next meeting and discuss avenues for improvements on that front.

**Comment by ScottMassa** [comment]
It’s hard to capture. I was talking to a user earlier this week and the plots hung. I click some and they are super fast and responsive. I think it might be when we pull in really large datasets such as pool and tailwater. not the CWMS ones.

**Comment by madisonschattenfield** [comment]
Currently unable to reproduce issue.

**Comment by madisonschattenfield** [comment]
Unable to reproduce issue and will reopen if we can get clear steps to reproduce.
