### ISSUE TITLE
[BUG REPORT]: OpenAPI Documentation

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#193]
## Describe the bug
Previously the BaseURL was https://midas.sec.usace.army.mil/api, now it is http://localhost:8080

## Expected behavior
Code snippets would return the API address

## Actual behavior
The code examples expect MIDAS to be run locally

## Screenshots
<img width="590" alt="image" src="https://github.com/user-attachments/assets/7a4128a4-40a6-4ad8-ac91-c77a61e62d54">

**Comment by dennisgsmith** [comment]
Fixed with https://github.com/USACE/instrumentation-api/releases/tag/v3.4.2
