### ISSUE TITLE
[BUG REPORT]: Advanced Plot Setting - Error on Saving Some Changes

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#195]
## Describe the bug
400 bad request error when modifying some timeseries symbology changes to remove markers. Logged out and back in to verify Keycloak/JWT token had not expired.

## Steps To Reproduce
Go to beaver dam, display plot for Monolith 13 Tiltmeter, Click advanced settings, turn off "markers", click save line settings. See red 400 Bad request error. 

## Expected behavior
Setting to be saved with no error

## Actual behavior
Error on API put.

## Screenshots
<img width="959" alt="image" src="https://github.com/user-attachments/assets/2f19f616-a9a9-48dd-927d-6ac44581ccb7">

## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 128

**Comment by dennisgsmith** [comment]
@KevinJJackson I tested this, the issue is that the payload does not include a hex code for the trace's color (must be a hex color, ie formatted as `#0099ff` for `plot_config.display.traces.color`)
