### ISSUE TITLE
[BUG REPORT]: Station Offset Type

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#200]
## Describe the bug
When uploading station and offset data in the uploader tool or editing on the "Edit Instrument" popup screen, type is limited to integer. We would like the type to be float, or similar, that allows storage of decimal values for both station and offset.

## Expected behavior
Storage of values with a decimal point.

## Actual behavior
Was limited to integer values

**Comment by dennisgsmith** [comment]
Values updated in API, awaiting changes to form field in UI

**Comment by KevinJJackson** [comment]
@dennisgsmith - Confirmed the UI accepts and passes floating point decimals: https://github.com/USACE/instrumentation-ui/blob/develop/src/common/forms/instrument-form.jsx#L284-L299
<img width="772" alt="image" src="https://github.com/user-attachments/assets/3b2de352-cec2-4f08-828d-903b24105a1c">

**Comment by dennisgsmith** [comment]
No UI changes needed, issue closed as complete
