### ISSUE TITLE
[BUG REPORT]: Rename Constants

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#206]
## Describe the bug
When renaming constants, they are not renamed, a new one is created instead

## Steps To Reproduce
1. Go to an instrument
2. Click on a constant, then edit button
3. revise name
4. save changes

## Expected behavior
the name will be changed

## Actual behavior
a new constant is created instead of revised name

## Screenshots
![image](https://github.com/user-attachments/assets/08fb14d0-a0fa-4152-b2a8-3d67402887f0)
![image](https://github.com/user-attachments/assets/1f80c7ce-c43f-47c7-9750-5ed4c54eb9ff)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser  Microsoft Edge
 - Version 131

**Comment by dennisgsmith** [comment]
Fixed with https://github.com/USACE/instrumentation-ui/releases/tag/v0.18.1
