### ISSUE TITLE
[BUG REPORT]: Adding and new timeseries, shows up in constants

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#207]
## Describe the bug
When adding a new timeseries to the timesieres tab, a new constant is created instead

## Steps To Reproduce
1. Go to Timeseries under instrument. Click "+ new timeseries" 
2. enter name and parameters, click "save changes"
3. new TS does not appear under Timeseries, but under Constants instead. 

## Expected behavior
Creates timeseries

## Actual behavior
Creates Constants instead

## Desktop (please complete the following information):
 - OS: Win 11
 - Browser Microsoft Edge
 - Version 131

**Comment by KevinJJackson** [comment]
Fixed in: https://github.com/USACE/instrumentation-ui/pull/233

https://github.com/USACE/instrumentation-ui/releases/tag/v0.18.1
