### ISSUE TITLE
[BUG REPORT]: Wording on New/Edit Constants and Timeseries

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#208]
## Describe the bug
A user was trying to delete timeseries and could not successfully delete them. 
They clicked edit, delete, confirm, then thought they should click save changes. 
The timeseries was deleted upon clicking confirm, then added back again without data when clicking "save changes"
Would recommend revising the "Save changes" button text to "Add timeseries", or "Add constant timeseries" on the constants screen.

Kevin, Does this sound reasonable? 

## Screenshots
![image](https://github.com/user-attachments/assets/96d0b7e6-abfd-4357-87a8-c12352e5ad8c)
## Desktop (please complete the following information):
 - OS: Win 11
 - Browser Microsoft Edge
 - Version 131

**Comment by dennisgsmith** [comment]
Fixed with https://github.com/USACE/instrumentation-ui/releases/tag/v0.18.1
