### ISSUE TITLE
[BUG REPORT]: Datalogger Field Mapping Table

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#212]
## Describe the bug
Can not add new timeseries mapping

## Steps To Reproduce
1. Go to datalogger
2. select a logger and a table
3. add instrument to field mapping table. - does not save. 
4. This timeseries is new and not on any other loggers. VWf from the logger, and VW Air Temp Timeseries

## Expected behavior
The Timeseries should show up and be saved in the mapping table. 

## Actual behavior
It does not save or error.

## Screenshots
![image](https://github.com/user-attachments/assets/f39427fd-55f2-4853-a320-b1e6f8c75b7d)

![image](https://github.com/user-attachments/assets/eb6fa3ac-8884-481f-a268-3e855f7b3ff4)

## Desktop (please complete the following information):
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 131

**Comment by KevinJJackson** [comment]
Fixed in API Release: https://github.com/USACE/instrumentation-api/releases/tag/v3.5.1
