### ISSUE TITLE
[BUG REPORT]: Timeseries Editing

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#215]
## Describe the bug
When editing a value on the timeseries tab, Time defaults to Year 0000, hiding the value from display. It cannot be deleted by the UI since it is not displayed. 

## Steps To Reproduce
1. Go to an instrument
2. Click on Timeseries tab
3. double click a reading, it will go to the edit view. If you click off of it will disappear since it will be on year 0000. 

## Expected behavior
Will be able to edit value 

## Actual behavior
the record is hidden, and date changed to the past. 

## Screenshots
![image](https://github.com/user-attachments/assets/7bc199db-def9-4589-b5ba-815e492f2743)

## Desktop (please complete the following information):
 - OS: Win 11
 - Browser Microsoft Edge
 - Version 131

**Comment by dennisgsmith** [comment]
This was cause due to a breaking change with a required AG Grid version upgrade.

Workaround: disabling date editor for timeseries fields. To edit a timeseries date, delete and recreate the row.

Revised editor will be scheduled for future release cycle.
