### ISSUE TITLE
[BUG REPORT]: Uploaded values not visible

### ISSUE THREAD

**Issue by ScottMassa** [USACE/instrumentation#217]
## Describe the bug
Data appears to upload, but cannot view data

## Steps To Reproduce
Upload tab, upload attached Airtemp_2.csv
Timestamp: IS08601
instrument: V, enabled
Map F1 values to the appropriate timeseries
![image](https://github.com/user-attachments/assets/f2fe565a-2e97-4647-a594-eafcd0117005)

## Expected behavior
Data to be uploaded, 

## Actual behavior
Data not observed as a timeseries, 
![image](https://github.com/user-attachments/assets/054e9e36-98e5-43de-87e2-484dbf7a30cd)
but may be observed in the collection groups window (51 degrees a month ago)
![image](https://github.com/user-attachments/assets/9d5100fd-1992-4f64-9516-80c1a5dc78fc)

## Screenshots

[Airtemp_2.csv](https://github.com/user-attachments/files/18170626/Airtemp_2.csv)

## Desktop (please complete the following information):
 - Browser [e.g. Microsoft Edge]
 - Version [e.g. 90.0.818.46]

**Comment by ScottMassa** [comment]
Also on production, another user can see the timeseries table and I cannot see any data. 
![47843063-d4c9-4cc4-be00-26ac1730a148](https://github.com/user-attachments/assets/dbdbde90-bcc9-4a6b-9005-06fccfa67c22)
vs 
![image](https://github.com/user-attachments/assets/a4cc6f54-1651-41b0-baf8-c40e88f6b6f0)
With a 500 Internal server error

**Comment by dennisgsmith** [comment]
Fix deployed: https://github.com/USACE/instrumentation-api/releases/tag/v3.5.2
