### ISSUE TITLE
POST /projects/:project_id/timeseries_measurements returns empty payload

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/instrumentation#25]
Update return payload from `{}` to an array of the timeseries and measurements successfully stored.  Empty return payload is problematic for the user interface.

**Comment by brettpalmberg** [comment]
@thill02 @KevinJJackson

**Comment by KevinJJackson** [comment]
I believe this can be closed, response is no longer empty:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/30411845/105056993-c5ee4400-5a42-11eb-8270-796e6a21c5e4.png">

**Comment by brettpalmberg** [comment]
Excellent!  Thank you for confirming.  Closing now.

cc @MegCQuinn @KevinJJackson @thill02
