### ISSUE TITLE
Regression Tests: Profile Validation Schema 

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/instrumentation#27]
Update the regression tests JSON validation schema for GET `{{ base_url }}/my_profile` to include `tokens` key/value in the payload.  Currently, `tokens` schema in the payload is not validated.  The `tokens` key is allowed using `additonalProperties: true`.

**Comment by dennisgsmith** [comment]
Planning migration away from Postman client since it's being sunsetted: https://blog.postman.com/announcing-new-lightweight-postman-api-client/

Migrating to [Echo tests](https://echo.labstack.com/docs/testing) and [Swaggo](https://github.com/swaggo/echo-swagger) for OpenAPI doc generation.
