### ISSUE TITLE
Endpoint to Update Instrument Latitude/Longitude

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/instrumentation#32]
Example: `PUT /instrumentation/projects/:project_id/instruments/:instrument_id/coordinates`

**Comment by adamscarberry** [comment]
PUT /instrumentation/projects/:project_id/instruments/:instrument_id/geometry

Tested with Airflow DAG updating MIDAS GPS coords from AWARE API.  Confirmed functionality works.
