### ISSUE TITLE
Wrong Page Numbers on Instrument Browser

### ISSUE THREAD

**Issue by lucasb16-exe** [USACE/instrumentation#34]
![PageIssue](https://user-images.githubusercontent.com/55309502/106181444-3a239880-6163-11eb-8d03-fbff1752fbfb.PNG)

Issue appears limited to projects with greater than 3 pages worth of instruments, repeats some page numbers and does not display others, will update issue with further investigation

**Comment by KevinJJackson** [comment]
Can you provide browser and OS that you are using?

I'm running:
MacOS 10.15.7
Firefox 84.0.2

and I'm not seeing this issue, looking at Herbert Hoover Dike locally:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/30411845/106182775-52001a00-616d-11eb-96d7-8551b2e7b0a8.png">

**Comment by KevinJJackson** [comment]
Was able to partially reproduce this by changing the items per pages dropdown value, however:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/30411845/106183411-2cbfdb80-616e-11eb-81cd-9cb7d160d03d.png">

**Comment by lucasb16-exe** [comment]
Issue was reported by onsite park ranger at Salamonie, I'm also seeing this on production running 
with 10 instruments per page. I'll test locally and report back as well.

Google Chrome Version 88.0.4324.96 - 64 bit
Windows 10 Enterprise Version 18363.1139

**Comment by KevinJJackson** [comment]
Think I found the cause, but if you could run this locally as well just to make sure. Looks like a typo when creating the inner pages of the pagination component:
https://github.com/USACE/instrumentation-ui/blob/develop/src/app-components/pager.js#L53

instead of `i + i`, it should be `i + 1`

**Comment by lucasb16-exe** [comment]
Closing with merge, thanks Kevin
