### ISSUE TITLE
User Interface; Instrument Group, Add Existing Instrument, Modal Picklist Enhacement

### ISSUE THREAD

**Issue by adamscarberry** [USACE/instrumentation#44]
I just added 40 existing instruments for the AWARE Pilot project to a group and it's pretty tedious adding more than a few at a time.

Current modal allow a single selection and disappears after clicking save changes (should that be "Add" ?)

Consider a multiple selection list where a user could use checkbox beside each selection.

Something like the concept below (no need for any type of hierarchy):

![multiple_select_checkbox_list](https://user-images.githubusercontent.com/46494851/107102664-2cb48100-67e9-11eb-93b3-bc1e7f382333.jpg)

Bonus points for a filter search box to help reduce choices before selection :-)

**Comment by KevinJJackson** [comment]
Hey @adamscarberry, I've been working on a multi-select component for the new batch plotting feature, does this seem like what you are looking for here as well:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/30411845/107571655-34916e00-6bb9-11eb-9f4b-3921ae859205.png">

I can spend some time making this filterable with input as well.

Which page/modal are you looking to see this added to?

**Comment by adamscarberry** [comment]
Yes, that looks perfect.  

Example instrument group page: https://apps.rsgis.dev/instrumentation/flood-sensor-program/groups/nwp

![image](https://user-images.githubusercontent.com/46494851/107572625-838bd300-6bba-11eb-8fd1-67883ea69cb9.png)

I think it's in app-pages/instrument-picker.js, but please double check that's correct.

Thanks @KevinJJackson !

**Comment by KevinJJackson** [comment]
Cool, I'll definitely take a look into this as soon as we get the batch-plotting code merged in (hopefully really soon with that!)

**Comment by KevinJJackson** [comment]
@adamscarberry I've opened a PR to get this implemented. If you have no quarrels with the way this looks, I'll go ahead a merge. If there is anything else that you'd like added or changed once you've seen the implementation first hand, please let me know and I'll see what I can do.

https://github.com/USACE/instrumentation-ui/pull/66

<img width="909" alt="image" src="https://user-images.githubusercontent.com/30411845/109023175-8ee70000-768a-11eb-94bd-723d3ee95e14.png">

**Comment by KevinJJackson** [comment]
@adamscarberry Merged - As requested above, if you could provide feedback and if everything looks good, close at your discretion. Thanks!
