### ISSUE TITLE
Map Not Resizing on Splitscreen Adjustments

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/instrumentation#55]

**Comment by brettpalmberg** [comment]
![image](https://user-images.githubusercontent.com/29417036/107823648-bdd5ab80-6d45-11eb-8563-78860a6f9f93.png)

**Comment by KevinJJackson** [comment]
Will have a fix for this shortly, looks like it got missed during a refactor of the class into a functional component.

**Comment by KevinJJackson** [comment]
Please verify the issue you were seeing has been resolved. Thank you!
