### ISSUE TITLE
Crash Upon Accessing Instrument Page

### ISSUE THREAD

**Issue by lucasb16-exe** [USACE/instrumentation#57]
![InstrumentReport](https://user-images.githubusercontent.com/55309502/108100618-c7178e80-704b-11eb-93b3-2f304086fc6e.PNG)

Crashing when accessing any instrument page within a project, error started occurring after uploading timeseries to Indiana Harbor instruments via the .csv uploader.

Accessing any instrument from any project is causing a crash

**Comment by KevinJJackson** [comment]
@lucasb16-exe Can this be closed?

**Comment by lucasb16-exe** [comment]
Yep, resolving now, thanks!
