### ISSUE TITLE
New Images for LRC-Chicago District Project Cards

### ISSUE THREAD

**Issue by lucasb16-exe** [USACE/instrumentation#8]
Upload new images for projects...
- Thomas J. O'brien Lock and Dam
- Lower Appleton Locks and Dam
- Upper Appleton Dam
- Cedars Lock and Dam
- Chicago River and Harbor Controlling Works
- DePere Lock and Dam
- Chicago Sanitary and Shipping Canal Fish Barrier
- Indiana Harbor 
- J Edward Roush Dam
- J Edward Roush Dam - Markle Levee
- Kaukauna Locks and Dam
- Little Kaukauna Lock and Dam
- Little Chute Locks and Dam
- Lockport Lock and Controlling Works
- Menasha Lock
- Mississinewa Dam
- Rapid Croche Lock and Dam
- Salamonie Dam

Find named images in the attached file
[ChicagoDistrictProjectPictures.zip](https://github.com/USACE/instrumentation-ui/files/5638309/ChicagoDistrictProjectPictures.zip)

**Comment by brettpalmberg** [comment]
Related to #9 .  Working on this now.

**Comment by lucasb16-exe** [comment]
Find renamed images attached
[ChicagoDistrictProjectPictures (2).zip](https://github.com/USACE/instrumentation/files/5771914/ChicagoDistrictProjectPictures.2.zip)

**Comment by lucasb16-exe** [comment]
Images updated for LRC Chicago, closing issue
